"""Professional Core V2 -- Multi-Turn Conversation Context Contract V1.

OFFLINE DOMAIN CONTRACT ONLY. This module defines a small, immutable,
provenance-preserving transport for PRIOR conversation turns, entirely
separate from the current-turn `source_text` every model-facing stage
already accepts. It performs no I/O of any kind: no network call, no model
call, no database access, no Telegram delivery, no environment reads, no
secret access, no filesystem access, no time/random behavior. It is not
imported by bot.py, is not wired into conversation_controller.py, and
persists nothing. There is no runtime wiring in this slice -- how a future,
separately authorized runtime turns real `messages` rows into this contract
is explicitly out of scope here; this module only defines what a valid
context object IS and what it may never contain.

WHY THIS EXISTS -- professional_turn_analyzer.call_turn_analyzer,
professional_turn_plan_proposer.call_turn_plan_proposer, and
professional_turn_response_renderer.render_turn_response are all
deliberately current-turn-only in their existing, still-unmodified public
contracts (see each module's own docstring). That is correct for a single
isolated turn, but makes a genuine multi-turn exchange impossible to handle
well: a short "да"/"нет" reply, an explicit correction, or a continuation
of an already-open exchange cannot be understood in isolation. This module
is the bounded, closed vocabulary those three call sites may now optionally
accept alongside (never instead of, never merged into) `source_text`.

CURRENT source_text IS UNCHANGED -- every one of the three call sites keeps
`source_text` (or `analysis_result`, for the Plan Proposer) as the sole,
untouched carrier of the genuine current-turn user message. This module's
context object is ALWAYS a separate, optional, keyword-only parameter.
Nothing in this repository concatenates conversation_context into
source_text, and nothing here provides an API shaped to invite that (no
`to_source_text`, no `as_prompt_prefix`, no string-joining helper of any
kind).

WHAT A CONTEXT OBJECT MAY CONTAIN -- exactly, and only:
  - `message_row_id`: a positive int identifying the already-persisted
    `messages` row this turn came from (provenance, not a display field).
  - `role`: exactly one of the two closed ConversationTurnRole members.
  - `content`: the exact, unmodified text of that already-delivered turn.

WHAT A CONTEXT OBJECT MAY NEVER CONTAIN (each one either structurally
impossible by this module's closed 3-field shape, or explicitly never
produced by anything in this file):
  - the current user's message itself -- a context object holds PRIOR
    turns only; the caller must never include the turn currently being
    analyzed/planned/rendered.
  - any role other than USER or ASSISTANT -- there is no SYSTEM member on
    ConversationTurnRole at all, so a system/tool/developer-role turn is
    not a value this type can represent, not merely a value it rejects.
  - hidden model state of any kind.
  - an LLM-generated rolling summary (e.g. memory.py's own summarization
    output) -- that text is itself an ungoverned model artifact, not a
    genuine prior turn, and must never be wrapped as if it were one.
  - a user profile or latent profile of any kind.
  - a stored psychological case-concept record or a core memory item (this
    repository's own separate, not-yet-wired case-concept / core_memory_items
    persistence layer) -- those carry their own MemoryLifecycle confirmation
    gate and are a separate concern this module does not touch or represent.
  - Telegram metadata (chat id, message id, callback data, usernames).
  - a callback value of any kind (a button tap is a trusted UI selection,
    never a conversational turn -- see professional_turn_ui_context.py).
  - an Entry Triage category selection.
  - secret or configuration data of any kind.

TRUST SEMANTICS -- read carefully, this is the single most important
contract in this module. A ConversationTurn is trusted ONLY as TRANSPORT
PROVENANCE: it is an exact record of what was actually, genuinely
persisted and delivered in a real prior turn. It is explicitly NOT trusted
as psychological truth about the user, and the two trust levels differ by
role:
  - Prior role=USER content means exactly: "the user previously said
    this." It carries the same (lack of) semantic trust as the current
    turn's own source_text -- genuine user-authored data, not yet
    professionally validated, but honestly attributed to the user.
  - Prior role=ASSISTANT content means exactly: "the assistant previously
    said/asked this." It is a record of the SYSTEM's own prior output. A
    prior assistant turn may state a question, a reflection, or (in
    principle) some other prior claim -- and that claim, having been
    generated by a probabilistic model, is NEVER thereby evidence that the
    claim is true about the user. A future Analyzer/Renderer consumer of
    this context must use assistant turns only to know what was already
    said/asked (so it does not repeat itself, and so it can recognize a
    reply as a continuation of a specific prior exchange) -- never as a
    confirmed fact folded into the user's own evidentiary record. This
    module cannot enforce that downstream discipline by itself (it is a
    pure transport type), which is exactly why every future consumer's own
    module docstring and model system-instruction must restate it
    explicitly -- see professional_turn_analyzer.py, professional_turn_
    plan_proposer.py, and professional_turn_response_renderer.py's own
    updated documentation for where that restatement now lives.

FROZEN V1 BOUNDS -- deliberately small, deliberately explicit, and
deliberately enforced by FAILING CLOSED (raising ValueError) rather than by
silently truncating or rewriting content. This module never mutates
included text to manufacture a fake "complete" history -- a caller facing
more raw material than these bounds allow must itself choose which turns
to omit BEFORE constructing this object (see OMISSION POLICY below); this
module's own job is only to reject a batch that doesn't already fit,
never to silently trim it into shape.
  - MAX_CONTEXT_TURNS = 8: mirrors this repository's own existing
    memory.py `KEEP` window (the number of most-recent raw turns the
    legacy memory builder already keeps verbatim) for consistency with an
    established, already-reviewed precedent -- not re-imported here (this
    module stays fully standalone/offline), just numerically aligned.
  - MAX_TURN_CONTENT_CHARS = 2000: mirrors professional_turn_response_
    renderer.MAX_CANDIDATE_TEXT_CHARS, the existing cap this repository
    already applies to one rendered professional turn -- a prior turn
    (whether a past assistant candidate or a past user message) is bounded
    at the same order of magnitude as a single turn is already bounded
    everywhere else in this codebase.
  - MAX_TOTAL_CONTEXT_CHARS = 4000: a genuinely bounded total payload --
    exactly two turns at the individual cap, or (far more realistically,
    since this module's own stated use cases are short replies,
    corrections, and continuations) several genuinely short turns. This
    keeps the model-facing payload small and cheap even in the worst case,
    and makes the per-turn cap the binding constraint only for unusually
    long individual turns, not the common case.

OMISSION POLICY: when raw material exceeds these bounds, prefer
deterministic omission of the OLDEST turns first, always preserving the
EXACT, unmodified content of whichever newer turns remain included. Never
truncate a turn's content to make it fit; either the whole turn is
included exactly as persisted, or it is omitted entirely.

PROFESSIONAL RUNTIME HISTORY BUILDER V1 (this slice) -- adds exactly one
pure function, build_conversation_context_from_history_rows, that applies
the OMISSION POLICY above over already-fetched plain rows and returns a
ProfessionalConversationContext. It performs no I/O of its own: the DB read
(database.get_professional_conversation_history_rows) is a separate,
already-bounded, already-provenance-filtered query that lives in
database.py, never here -- this module's own "no I/O anywhere" contract is
unchanged. The builder independently re-validates role/source on every row
rather than trusting the caller's own filtering, so a raw row whose source
is not exactly the value TRUSTED for its own role (see TRUST SEMANTICS
above) is excluded, not reinterpreted -- defense in depth against a future
caller that bypasses or misuses the DB-side filter. Still no runtime
wiring: nothing in this repository calls this function from bot.py as of
this slice.

Only imports: __future__, dataclasses, enum. No bot.py import, no
conversation_controller.py import, no database import, no Telegram import,
no model/network import. Python 3.10 target (prod 3.10.12): `str, Enum`
mix-ins, not `StrEnum` (3.11+).
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

# -- Frozen V1 engineering bounds -- see module docstring for rationale. ---
MAX_CONTEXT_TURNS = 8
MAX_TURN_CONTENT_CHARS = 2000
MAX_TOTAL_CONTEXT_CHARS = 4000


class ConversationTurnRole(str, Enum):
    """Closed V1 role vocabulary -- exactly two members. There is no SYSTEM
    (or any other) member: a system/tool/developer-authored turn is not a
    value this type can represent at all, structurally, not merely a value
    validation happens to reject."""
    USER = "USER"
    ASSISTANT = "ASSISTANT"


@dataclass(frozen=True)
class ConversationTurn:
    """One already-persisted, already-delivered prior conversation turn.
    Trusted only as exact transport provenance -- see TRUST SEMANTICS in
    the module docstring. Never the current turn being analyzed, planned,
    or rendered."""
    message_row_id: int
    role: ConversationTurnRole
    content: str

    def __post_init__(self):
        if type(self.message_row_id) is not int:
            raise ValueError(
                "ConversationTurn.message_row_id must be an int, got "
                f"{type(self.message_row_id)!r}")
        if self.message_row_id <= 0:
            raise ValueError(
                "ConversationTurn.message_row_id must be a positive int, "
                f"got {self.message_row_id!r}")
        if type(self.role) is not ConversationTurnRole:
            raise ValueError(
                "ConversationTurn.role must be exactly a ConversationTurnRole, "
                f"got {type(self.role)!r}")
        if type(self.content) is not str:
            raise ValueError(
                f"ConversationTurn.content must be a str, got {type(self.content)!r}")
        if not self.content or not self.content.strip():
            raise ValueError(
                "ConversationTurn.content must be non-empty and not whitespace-only")
        if len(self.content) > MAX_TURN_CONTENT_CHARS:
            raise ValueError(
                "ConversationTurn.content exceeds the "
                f"{MAX_TURN_CONTENT_CHARS}-character V1 per-turn bound "
                f"(got {len(self.content)} characters) -- a future caller must "
                "omit this turn entirely rather than truncate it")


@dataclass(frozen=True)
class ProfessionalConversationContext:
    """An ordered, bounded tuple of PRIOR conversation turns only -- the
    current user message is never included (see the module docstring's
    WHAT A CONTEXT OBJECT MAY NEVER CONTAIN section). Turns must already be
    in chronological order with strictly increasing message_row_id values
    (this is both the ordering proof and the duplicate/out-of-order
    rejection in one check, since these are real autoincrement row ids).
    Fails closed on any bound violation -- never silently reorders,
    deduplicates, truncates, or drops a turn to make an invalid batch fit;
    that decision belongs to whichever future caller constructs the tuple
    in the first place (see OMISSION POLICY in the module docstring)."""
    turns: tuple[ConversationTurn, ...]

    def __post_init__(self):
        if type(self.turns) is not tuple:
            raise ValueError(
                f"ProfessionalConversationContext.turns must be a tuple, "
                f"got {type(self.turns)!r}")
        for turn in self.turns:
            if type(turn) is not ConversationTurn:
                raise ValueError(
                    "ProfessionalConversationContext.turns entries must be "
                    f"ConversationTurn, got {type(turn)!r}")
        if len(self.turns) > MAX_CONTEXT_TURNS:
            raise ValueError(
                "ProfessionalConversationContext.turns exceeds the "
                f"{MAX_CONTEXT_TURNS}-turn V1 bound (got {len(self.turns)} turns)")
        row_ids = [turn.message_row_id for turn in self.turns]
        if any(row_ids[i] >= row_ids[i + 1] for i in range(len(row_ids) - 1)):
            raise ValueError(
                "ProfessionalConversationContext.turns must be in strict "
                "chronological order (strictly increasing message_row_id); "
                f"got {row_ids!r}")
        total_chars = sum(len(turn.content) for turn in self.turns)
        if total_chars > MAX_TOTAL_CONTEXT_CHARS:
            raise ValueError(
                "ProfessionalConversationContext total content exceeds the "
                f"{MAX_TOTAL_CONTEXT_CHARS}-character V1 bound "
                f"(got {total_chars} characters across {len(self.turns)} turns)")

    @property
    def is_empty(self) -> bool:
        return len(self.turns) == 0


EMPTY_CONVERSATION_CONTEXT = ProfessionalConversationContext(turns=())


# Mirrors (does not import) database.MessageSource's two conversation-safe
# values -- see PROFESSIONAL RUNTIME HISTORY BUILDER V1 in the module
# docstring. Kept as plain strings, not an Enum imported from database.py,
# to preserve this module's own closed import contract (only __future__,
# dataclasses, enum -- see test_module_imports_only_allowed_roots). If
# database.MessageSource's frozen vocabulary ever changes, this mapping
# must be updated in lockstep; it is intentionally not the single source of
# truth for that vocabulary, only this module's own defense-in-depth check.
_TRUSTED_SOURCE_BY_ROLE = {
    ConversationTurnRole.USER: "USER_AUTHORED",
    ConversationTurnRole.ASSISTANT: "ASSISTANT_DELIVERED",
}


def build_conversation_context_from_history_rows(rows) -> ProfessionalConversationContext:
    """Pure, synchronous builder: turns already-fetched plain history rows
    into a ProfessionalConversationContext by applying the OMISSION POLICY
    (module docstring) and the FROZEN V1 BOUNDS. No I/O of any kind -- the
    caller (database.get_professional_conversation_history_rows) is
    responsible for the actual DB read, the id < current_source_message_
    row_id upper bound, and the source IN ('USER_AUTHORED',
    'ASSISTANT_DELIVERED') filter; this function trusts none of that by
    itself (see PROVENANCE DEFENSE IN DEPTH below).

    `rows` -- any iterable of (message_row_id, role, content, source)
    4-tuples, exactly the shape database.get_professional_conversation_
    history_rows returns, in ascending message_row_id order. `role` is the
    raw stored string ("user" / "assistant" / anything else); `source` is
    the raw stored `messages.source` value (a MessageSource.value string,
    or None for legacy/unknown provenance).

    PROVENANCE DEFENSE IN DEPTH -- every row is independently re-validated
    here, not merely trusted from the caller's own SQL filter: a row is
    excluded (never reinterpreted) unless its `source` is EXACTLY the one
    TRUSTED value for its own `role` (USER_AUTHORED only for role='user',
    ASSISTANT_DELIVERED only for role='assistant'). A mismatched pair
    (e.g. USER_AUTHORED with role='assistant'), a SYNTHETIC_UI row, a
    source IS NULL / UNKNOWN_LEGACY_PROVENANCE row, or any unrecognized
    future source value are all excluded on the same path -- this function
    never infers the "intended" role from source, and never infers
    provenance from role. This is what makes it safe to call even if a
    future caller (by mistake, in a test, or via a bypassed query) hands
    this function rows that were not actually filtered upstream.

    Never truncates, never summarizes, never merges or deduplicates turns,
    never invents alternation, never reorders input -- if the surviving
    rows are not already in strictly increasing message_row_id order (or
    contain a duplicate id), ProfessionalConversationContext's own
    __post_init__ fails closed with ValueError; this function does not
    pre-sort or de-duplicate to paper over that.

    No model call, no source_text parameter, no current-turn text
    concatenation -- this function only ever sees PRIOR rows the caller
    already excluded the current turn from."""
    eligible = []
    for message_row_id, role, content, source in rows:
        if type(message_row_id) is not int or message_row_id <= 0:
            continue
        if role == "user":
            turn_role = ConversationTurnRole.USER
        elif role == "assistant":
            turn_role = ConversationTurnRole.ASSISTANT
        else:
            continue
        if source != _TRUSTED_SOURCE_BY_ROLE[turn_role]:
            continue
        if type(content) is not str or not content.strip():
            continue
        if len(content) > MAX_TURN_CONTENT_CHARS:
            continue
        eligible.append((message_row_id, turn_role, content))

    if len(eligible) > MAX_CONTEXT_TURNS:
        eligible = eligible[-MAX_CONTEXT_TURNS:]

    total_chars = sum(len(content) for _row_id, _role, content in eligible)
    while total_chars > MAX_TOTAL_CONTEXT_CHARS and eligible:
        _dropped_id, _dropped_role, dropped_content = eligible.pop(0)
        total_chars -= len(dropped_content)

    turns = tuple(
        ConversationTurn(message_row_id=row_id, role=role, content=content)
        for row_id, role, content in eligible)
    return ProfessionalConversationContext(turns=turns)
