"""Push V1 (Round 5) — real aiogram dispatcher-level tests for cb_push_action
(the "pushbtn:" callback handler), following the exact same real-dispatch
technique as tests/test_journal_navigation_dispatch.py: a real Update is fed
through bot.dp.feed_update(bot.bot, update) so actual filter/handler
resolution is exercised, not just a direct function call.

The push itself is generated by the REAL send path
(scheduler._send_silence_pushes(bot.bot), through the SAME stub session),
so the token/chat_id/message_id used to build the tap Update are exactly
what production would hand back to Telegram -- not hand-constructed.

Covers task §13's lettered scenarios (E: crisis-after-delivery,
F: access-revoked-after-delivery, G: onboarding-active-after-delivery) plus
the Continue/New-topic valid paths and the no-fabricated-free-text /
no-first-turn-misclassification guarantees. A/B/C/D (stale revision, double
tap, sibling invalidation, old-push-superseded) are already covered at the
DB layer in tests/test_push_v1_bindings.py -- this file focuses on what
ONLY a real dispatch can prove: gate ordering inside the actual callback
route.
"""
import asyncio
import itertools
import time

import pytest

import access_control as ac
import bot
import config
import database
import prompts
import scheduler
from crisis_protocol import crisis_screen
from aiogram.client.session.base import BaseSession
from aiogram.methods.base import Response
from aiogram.types import Update

USER_ID = 777333

_id_counter = itertools.count(1)


class _StubSession(BaseSession):
    def __init__(self):
        super().__init__()
        self.sent = []

    async def close(self):
        pass

    async def make_request(self, bot_, method, timeout=None):
        self.sent.append(method)
        returning = method.__returning__
        if returning is bool:
            data = {"ok": True, "result": True}
        else:
            data = {"ok": True, "result": {
                "message_id": next(_id_counter),
                "date": int(time.time()),
                "chat": {"id": USER_ID, "type": "private"},
                "text": getattr(method, "text", "") or "",
            }}
        resp = Response[returning].model_validate(data, context={"bot": bot_})
        return resp.result

    async def stream_content(self, *a, **kw):
        raise NotImplementedError

    def texts(self):
        return [getattr(m, "text", None) for m in self.sent]


def _async(value=None):
    async def _f(*a, **kw):
        return value
    return _f


@pytest.fixture
def tmp_db(tmp_path, monkeypatch):
    monkeypatch.setattr(database, "DB", str(tmp_path / "push_cb.db"))
    run = asyncio.run
    run(database.init_db())
    return database


@pytest.fixture(autouse=True)
def _common(monkeypatch, tmp_db):
    monkeypatch.setattr(bot, "get_user_language", _async("ru"))
    monkeypatch.setattr(bot, "get_active_crisis", _async(None))
    monkeypatch.setattr(bot, "log_crisis_delivery", _async(None))
    monkeypatch.setattr(ac, "DEPLOYMENT_MODE", "personal_use")
    monkeypatch.setattr(ac, "OWNER_USER_ID", USER_ID)
    monkeypatch.setattr(ac, "CLINICIAN_TESTER_IDS", set())
    monkeypatch.setattr(ac, "CLINICIAN_REVIEWER_IDS", set())
    monkeypatch.setattr(ac, "TESTER_REVIEWER_MAP", {})
    monkeypatch.setattr(config, "FIRST_USER_ONBOARDING_ENABLED", False)
    stub = _StubSession()
    monkeypatch.setattr(bot.bot, "session", stub)
    return stub


def _make_callback_update(data, message_id, chat_id=USER_ID, uid=USER_ID):
    return Update.model_validate({
        "update_id": next(_id_counter),
        "callback_query": {
            "id": str(next(_id_counter)),
            "from": {"id": uid, "is_bot": False, "first_name": "T"},
            "message": {
                "message_id": message_id,
                "date": int(time.time()),
                "chat": {"id": chat_id, "type": "private"},
                "text": "placeholder",
            },
            "chat_instance": "1",
            "data": data,
        },
    }, context={"bot": bot.bot})


async def _seed_inactive_user(uid=USER_ID, days_inactive=2):
    await database.upsert_user(uid, "u", "U", "ru")
    async with database.aiosqlite.connect(database.DB) as db:
        await db.execute(
            "UPDATE users SET last_seen=datetime('now', ?) WHERE id=?",
            (f"-{days_inactive} days", uid))
        await db.commit()


async def _seed_conversation_anchor(uid=USER_ID):
    """A genuine prior conversational assistant turn -- required for the
    scheduler to send the Push V1 card at all (Correction #1, Blocker 5).
    Returns the new messages row id."""
    return await database.save_message(
        uid, "assistant", "prior reply", "open_chat", "ru",
        source=database.MessageSource.ASSISTANT_DELIVERED)


async def _deliver_real_push(stub, uid=USER_ID, with_anchor=True):
    """Drives the REAL send path (scheduler._send_silence_pushes) through
    the SAME stub session bot.py's dispatcher uses, so the resulting
    chat_id/message_id/tokens are exactly what production would hand back
    to Telegram -- never hand-constructed. Seeds a real conversation anchor
    by default (with_anchor=True) since the scheduler now refuses to send
    at all without one (Correction #1, Blocker 5) -- callers testing
    anchor semantics themselves pass with_anchor=False or manage the
    anchor row directly. Returns
    (chat_id, message_id, continue_token, new_topic_token)."""
    await _seed_inactive_user(uid)
    if with_anchor:
        await _seed_conversation_anchor(uid)
    await scheduler._send_silence_pushes(bot.bot)
    async with database.aiosqlite.connect(database.DB) as db:
        cur = await db.execute(
            "SELECT token, action, chat_id, source_message_id FROM push_action_bindings "
            "WHERE user_id=? AND consumed_at IS NULL AND superseded_at IS NULL", (uid,))
        rows = await cur.fetchall()
    by_action = {r[1]: r for r in rows}
    assert set(by_action) == {"push_continue", "push_new_topic"}, \
        "push delivery did not produce the expected 2 open bindings"
    chat_id = by_action["push_continue"][2]
    message_id = by_action["push_continue"][3]
    return chat_id, message_id, by_action["push_continue"][0], by_action["push_new_topic"][0]


# ── Continue / New-topic valid paths ────────────────────────────────────────
def test_continue_valid_path_with_anchor_sends_resume_opener(_common):
    async def run():
        # _deliver_real_push seeds a real anchor by default.
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))
    asyncio.run(run())
    assert prompts.PUSH_V1_CONTINUE_REPLY_RU in _common.texts()


# ── Correction #1, Blocker 5.D: anchor existed at SEND time, then is
# deleted before the Continue tap -- the callback must safely degrade to
# the neutral no-anchor fallback and invent nothing. ────────────────────────
def test_anchor_deleted_between_send_and_tap_degrades_to_neutral_fallback(_common):
    async def run():
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        # Simulate a privacy deletion (or any other state change) removing
        # the SPECIFIC anchored row between push-send and the Continue tap.
        async with database.aiosqlite.connect(database.DB) as db:
            await db.execute("DELETE FROM messages WHERE user_id=?", (USER_ID,))
            await db.commit()
        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))
    asyncio.run(run())
    texts = _common.texts()
    assert prompts.PUSH_V1_NO_ANCHOR_REPLY_RU in texts
    assert prompts.PUSH_V1_CONTINUE_REPLY_RU not in texts  # never a fabricated "resume"


def test_new_topic_valid_path(_common):
    async def run():
        chat_id, message_id, _, new_topic_token = await _deliver_real_push(_common)
        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{new_topic_token}", message_id, chat_id))
    asyncio.run(run())
    assert prompts.PUSH_V1_NEW_TOPIC_REPLY_RU in _common.texts()


def test_neither_button_writes_a_fabricated_user_message(_common):
    async def run():
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))
        async with database.aiosqlite.connect(database.DB) as db:
            cur = await db.execute(
                "SELECT COUNT(*) FROM messages WHERE user_id=? AND role='user'", (USER_ID,))
            row = await cur.fetchone()
        return row[0]
    user_message_count = asyncio.run(run())
    assert user_message_count == 0  # a trusted UI tap is never persisted as user free text


# ── §13.E / Correction #1 Blocker 1: crisis starts after delivery, and
# remains unresolved past get_active_crisis()'s 24h window -- the crisis
# screen must still win, using the REAL unresolved-crisis lifecycle
# (get_unresolved_crisis), not the 24h-bounded interactive gate. ───────────
def test_crisis_unresolved_over_24h_after_delivery_blocks_and_reshows_screen(_common):
    async def run():
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        # A crisis starts AFTER the push was already delivered...
        eid = await database.log_crisis_event(
            USER_ID, "critical", 10, ["suicide"], "x", "ru")
        # ...and remains unresolved past the OLD 24h-only window (this is
        # exactly the gap Blocker 1 closes: get_active_crisis(uid) alone
        # would return None here, since its default window is 24h).
        async with database.aiosqlite.connect(database.DB) as db:
            await db.execute(
                "UPDATE crisis_events SET created_at=datetime('now','-30 hours') "
                "WHERE id=?", (eid,))
            await db.commit()
        events_before = await _crisis_event_count()

        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))

        events_after = await _crisis_event_count()
        result = await database.consume_push_action_binding(
            continue_token, USER_ID, chat_id, message_id)
        return eid, events_before, events_after, result
    eid, events_before, events_after, result = asyncio.run(run())

    # normal Continue/New-topic reply is NOT sent:
    assert prompts.PUSH_V1_CONTINUE_REPLY_RU not in _common.texts()
    assert prompts.PUSH_V1_NO_ANCHOR_REPLY_RU not in _common.texts()
    # binding is not normally consumable afterward (best-effort supersession):
    assert result is None
    # the EXISTING crisis safety surface (the real crisis screen for THIS
    # exact event) was produced, not a silent no-op:
    expected_text, _kb = crisis_screen(0, "ru", eid)
    assert expected_text in _common.texts()
    # no second crisis_events row was created:
    assert events_after == events_before


async def _crisis_event_count():
    async with database.aiosqlite.connect(database.DB) as db:
        cur = await db.execute("SELECT COUNT(*) FROM crisis_events")
        row = await cur.fetchone()
    return row[0]


# ── §13.F: ordinary access revoked after delivery -- no normal continuation
def test_access_revoked_after_delivery_blocks_continuation(monkeypatch, _common):
    async def run():
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        # Revoke access for the CONSUME side only -- the push above was
        # already delivered while access was valid (_common's fixture makes
        # USER_ID the owner, so DEPLOYMENT_MODE/role-constant games can't
        # revoke an owner's access; patch the gate function itself instead,
        # exactly modeling "access was later revoked by other means").
        monkeypatch.setattr(ac, "has_full_access", _async(False))
        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))
    asyncio.run(run())
    assert prompts.PUSH_V1_CONTINUE_REPLY_RU not in _common.texts()
    assert prompts.PUSH_V1_NO_ANCHOR_REPLY_RU not in _common.texts()


# ── §13.G: mandatory onboarding becomes active -- cannot be bypassed
def test_active_onboarding_after_delivery_blocks_continuation(monkeypatch, _common):
    async def run():
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        monkeypatch.setattr(bot, "_onboarding_blocks_ordinary_entry", _async(True))
        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))
    asyncio.run(run())
    assert prompts.PUSH_V1_CONTINUE_REPLY_RU not in _common.texts()
    assert prompts.PUSH_V1_NO_ANCHOR_REPLY_RU not in _common.texts()


# ── active journal FSM is abandoned (not contaminated) on a valid tap ──────
def test_continue_tap_clears_a_stale_active_journal_fsm(_common):
    async def run():
        chat_id, message_id, continue_token, _ = await _deliver_real_push(_common)
        # Seed a real, active EmotionJournal FSM via the SAME MemoryStorage
        # the real dispatcher resolves for this (bot, chat, user) -- mirrors
        # tests/test_journal_navigation_dispatch.py's technique.
        ctx = bot.dp.fsm.get_context(bot.bot, chat_id=USER_ID, user_id=USER_ID)
        await ctx.set_state(bot.EmotionJournal.active)
        await ctx.set_data({"jstep": 1, "jdata": {"event": "x"}, "orange": False, "nudged": False})

        await bot.dp.feed_update(
            bot.bot, _make_callback_update(f"pushbtn:{continue_token}", message_id, chat_id))
        return ctx
    ctx = asyncio.run(run())
    assert asyncio.run(ctx.get_state()) is None
    assert asyncio.run(ctx.get_data()) == {}
    # _deliver_real_push seeds a real anchor by default, so the resume
    # opener is expected here -- this test's own concern is the journal
    # FSM clear above, not anchor semantics (covered separately).
    assert prompts.PUSH_V1_CONTINUE_REPLY_RU in _common.texts()
